version: "3.4"
services:
  hived:
    image: hived
    build:
      context: ./hived
    secrets:
      - ch_api_key
      - ch_api_secret
      - tg_bot_token
    networks:
      - mainnet
      - telenet
    restart: unless-stopped
    ports:
      - "8008:8008"
    depends_on:
      - redis
      - telebot
    entrypoint: ["/hived/docker-entrypoint.sh"]
    volumes:
      - /etc/letsencrypt/archive/api.terminaldweller.com/:/certs/
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
  telebot:
    image: telebot
    build:
      context: ./telebot
    secrets:
      - tg_bot_token
    networks:
      - telenet
    restart: unless-stopped
    ports:
      - "127.0.0.1:9009:9009"
    entrypoint: ["/telebot/docker-entrypoint.sh"]
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
  redis:
    image: redis:6.2-alpine
    networks:
      - mainnet
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data/
networks:
  mainnet:
    driver: bridge
  telenet:
    driver: bridge
secrets:
  tg_bot_token:
    file: ./tgtoken
  ch_api_key:
    file: ./changelly_api_key
  ch_api_secret:
    file: ./changelly_api_secret
volumes:
  redis-data:
