services:
  nginx:
    image: waf
    build:
      context: .
      dockerfile: Dockerfile_waf
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    ports:
      - "8007:443/tcp"
    networks:
      apinet:
        ipv4_address: 172.31.89.10
    restart: unless-stopped
    environment:
      - MODSECURITY_RULE_ENGINE=On
      - BLOCKING_PARANOIA=1
      - DETECTION_PARANOIA=1
      - ALLOWED_REQUEST_CONTENT_TYPE_CHARSET=|utf-8|
      - VALIDATE_UTF8_ENCODING=1
      - ALLOWED_METHODS=GET POST PUT DELETE
      - ALLOWED_HTTP_VERSIONS=HTTP/2.0
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/waf.conf:ro
    depends_on:
      - hived
    security_opt:
      - no-new-privileges
    runtime: runsc
  hived:
    image: hived
    build:
      context: ./hived
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    restart: unless-stopped
    networks:
      apinet:
        ipv4_address: 172.31.89.11
      dbnet:
        ipv4_address: 172.31.88.11
    ports:
      - "127.0.0.1:10009:8090/tcp"
    entrypoint: ["/hived/hived"]
    command: ["serve", "--http=0.0.0.0:8090"]
    depends_on:
      - redis
    cap_drop:
      - ALL
    environment:
      - HIVED_PRICE_SOURCE=cmc
      - CMC_API_KEY=
      - TELEGRAM_BOT_TOKEN=
    read_only: true
    volumes:
      - ./hived/hived.toml:/hived/hived.toml:ro
      - ./resolv.conf:/etc/resolv.conf:ro
      - pb-data:/hived/pb_data:rw
    security_opt:
      - no-new-privileges
    runtime: runsc
  redis:
    image: redis:8.8-alpine
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    networks:
      dbnet:
        ipv4_address: 172.31.88.10
    ports:
      - "127.0.0.1:6380:6379/tcp"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data/:rw
    security_opt:
      - no-new-privileges
    runtime: runsc
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
networks:
  dbnet:
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.88.0/24
  apinet:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.89.0/24
volumes:
  redis-data:
  pb-data:
