version: "3.4"
services:
  hived:
    image: hived
    build:
      context: ./
    secrets:
      - tg_bot_token
      - ch_api_key
      - ch_api_secret
    networks:
      - hivednet
    restart: unless-stopped
    ports:
      - "8008:8008"
    depends_on:
      - redis
    entrypoint: /hived/docker-entrypoint.sh
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=test
  redis:
    image: redis:6.2-alpine
    networks:
      - hivednet
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data/
networks:
  hivednet:
    driver: bridge
secrets:
  tg_bot_token:
    file: ./tgtoken
  ch_api_key:
    file: ./changelly_api_key
  ch_api_secret:
    file: ./changelly_api_secret
volumes:
  redis-data:
