services:
  hived:
    image: hived
    build:
      context: ./hived
    secrets:
      - tg_bot_token
    networks:
      - mainnet
      - telenet
    ports:
      - "10008:8008"
    depends_on:
      - redis
      - telebot
    entrypoint: ["/hived/docker-entrypoint.sh"]
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=test
      - POLYGON_API_KEY=
  telebot:
    image: telebot
    build:
      context: ./telebot
    secrets:
      - tg_bot_token
    networks:
      - telenet
    ports:
      - "10009:8000"
    entrypoint: ["/telebot/docker-entrypoint.sh"]
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=test
  arbiter:
    image: arbiter
    build:
      context: ./arbiter
    networks:
      - mainnet
    ports:
      - "8009:8009"
    entrypoint: ["/arbiter/arbiter"]
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=test
  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    networks:
      - mainnet
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # volumes:
    #   - redis-data:/data/
networks:
  mainnet:
    driver: bridge
  telenet:
    driver: bridge
secrets:
  tg_bot_token:
    file: ./tgtoken
volumes:
  redis-data:
