services:
  hived:
    image: hived
    build:
      context: ./hived
    secrets:
      - ch_api_key
      - ch_api_secret
      - tg_bot_token
    networks:
      - mainnet
      - telenet
    restart: unless-stopped
    ports:
      - "8007:8008"
    depends_on:
      - keydb
      - telebot
    entrypoint: ["/hived/docker-entrypoint.sh"]
    volumes:
      - /etc/letsencrypt/live/api.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/api.terminaldweller.com/fullchain.pem
      - /etc/letsencrypt/live/api.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/api.terminaldweller.com/privkey.pem
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
      - POLYGON_API_KEY=
  telebot:
    image: telebot
    build:
      context: ./telebot
    secrets:
      - tg_bot_token
    networks:
      - telenet
    restart: unless-stopped
    ports:
      - "127.0.0.1:9009:8000"
    entrypoint: ["/telebot/docker-entrypoint.sh"]
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    networks:
      - mainnet
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data/
  arbiter:
    image: arbiter
    build:
      context: ./arbiter
    networks:
      - mainnet
    ports:
      - "8009:8009"
    entrypoint: ["/arbiter/arbiter"]
    volumes:
      - /etc/letsencrypt/live/api.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/api.terminaldweller.com/fullchain.pem
      - /etc/letsencrypt/live/api.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/api.terminaldweller.com/privkey.pem
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
networks:
  mainnet:
    driver: bridge
  telenet:
    driver: bridge
secrets:
  tg_bot_token:
    file: ./tgtoken
  ch_api_key:
    file: ./changelly_api_key
  ch_api_secret:
    file: ./changelly_api_secret
volumes:
  redis-data:
