run:
  concurrency: 16
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.22'
linters-settings:
  depguard:
    rules:
      srcs:
        listMode: "Strict"
        allow:
        - $gostd
        - github.com/go-telegram-bot-api/telegram-bot-api
        - github.com/rs/zerolog/log
        - github.com/terminaldweller/grpc/telebot/v1
        - golang.org/x/net/proxy
        - google.golang.org/grpc
